name: 'CoreyCooperStevens | Creative Projects For Change '
favicon: null
layout_spectrum: 0.9414212459232658
typography_spectrum: 0.6588001851923764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.39085720432922244
  lightness: 0.27674576942808926
  saturation: 0.6107111140154302
  rhythmicContrast: 0.042465316597372293
purpose: []
