name: 'CoreyCooperStevens '
favicon: null
layout_spectrum: 0.9414212459232658
typography_spectrum: 0.85665
title: CoreyCooperStevens
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242221'
    - '#693348'
    - '#b13037'
    - '#a68283'
    - '#ffffc6'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
